2024-09-26 18:08:02.429216: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-26 18:08:02.429294: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-26 18:08:02.430757: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-26 18:08:02.438264: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-26 18:08:04.643185: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/datacommons/igvf-pm/K562/leave-one-out/BlueSTARR/cross-validation.py", line 217, in <module>
    main(configFile,subdir,modeldir,outdir)
  File "/datacommons/igvf-pm/K562/leave-one-out/BlueSTARR/cross-validation.py", line 47, in main
    config=NeuralConfig(configFile)
  File "/datacommons/igvf-pm/K562/leave-one-out/BlueSTARR/NeuralConfig.py", line 19, in __init__
    config=ConfigFile(filename)
  File "/hpc/home/yc583/envs/tf2/lib/python3.10/site-packages/ConfigFile.py", line 30, in __init__
    self.load(filename)
  File "/hpc/home/yc583/envs/tf2/lib/python3.10/site-packages/ConfigFile.py", line 52, in load
    with open(filename,"r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/datacommons/igvf-pm/K562/leave-one-out/config-mse/K562_Y.config'
